# Generated by Django 4.1.3 on 2023-04-26 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_budget_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='note',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='income',
            name='note',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='transfer',
            name='note',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
