# Generated by Django 4.1.3 on 2023-05-09 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('the_budget_app', '0002_expense_note_income_note_transfer_note'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ledger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_account', models.IntegerField(null=True)),
                ('amount', models.FloatField(default=0)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('date_created', models.DateTimeField()),
            ],
            options={
                'db_table': 'ledger',
            },
        ),
        migrations.RemoveField(
            model_name='income',
            name='account',
        ),
        migrations.RemoveField(
            model_name='income',
            name='category',
        ),
        migrations.RemoveField(
            model_name='transfer',
            name='from_account',
        ),
        migrations.RemoveField(
            model_name='transfer',
            name='to_account',
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
        migrations.AlterField(
            model_name='category',
            name='category_type',
            field=models.CharField(choices=[('income', 'Income'), ('expense', 'Expense'), ('transfer', 'Transfer')], max_length=8),
        ),
        migrations.AlterModelTable(
            name='account',
            table='account',
        ),
        migrations.AlterModelTable(
            name='budget',
            table='budget',
        ),
        migrations.AlterModelTable(
            name='category',
            table='category',
        ),
        migrations.DeleteModel(
            name='Expense',
        ),
        migrations.DeleteModel(
            name='Income',
        ),
        migrations.DeleteModel(
            name='Transfer',
        ),
        migrations.AddField(
            model_name='ledger',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='the_budget_app.account'),
        ),
        migrations.AddField(
            model_name='ledger',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='the_budget_app.category'),
        ),
    ]
