# Generated by Django 4.1.3 on 2023-05-12 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_budget_app', '0004_alter_account_amount_alter_ledger_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='amount',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='ledger',
            name='amount',
            field=models.FloatField(default=0),
        ),
    ]
