# Generated by Django 4.1.3 on 2023-05-18 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_budget_app', '0005_alter_account_amount_alter_ledger_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='editable',
            field=models.BooleanField(default=True),
        ),
    ]
